/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ignis66.vistas;

import Ignis66.entidades.Bombero;
import Ignis66.acessoADatos.BomberoData;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/** :P
 *
 * @author fdicocco
 */
public final class AltaBombero extends javax.swing.JFrame {

    /**
     * Creates new form PruebaFormularioBombero
     */
    public AltaBombero() {
        setBounds(230, 30, 600 , 600);
        initComponents();
        limpiarCampos();
        disableCopyPaste(jtfNombre);
        disableCopyPaste(jtfApellido);
        disableCopyPaste(jtfCelular);
        disableCopyPaste(jtfFijo);
        disableCopyPaste(jtfDni);
        disableCopyPaste(jtfCorreo);
        disableCopyPaste(jdcFechaNac);
        
        
        validacion();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfDni = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jtfCelular = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jcbRango = new javax.swing.JComboBox<>();
        jcbSangre = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jtfCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtfFijo = new javax.swing.JTextField();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jlErrorNombre = new javax.swing.JLabel();
        jlErrorApellido = new javax.swing.JLabel();
        jlErrorDni = new javax.swing.JLabel();
        jlErrorSexo = new javax.swing.JLabel();
        jlErrorFecha = new javax.swing.JLabel();
        jlErrorCelular = new javax.swing.JLabel();
        jlErrorFijo = new javax.swing.JLabel();
        jlErrorCorreo = new javax.swing.JLabel();
        jlErrorTipo = new javax.swing.JLabel();
        jlErrorSangre = new javax.swing.JLabel();
        jlErrorRango = new javax.swing.JLabel();
        jlErrorEstado = new javax.swing.JLabel();
        jrbFijo = new javax.swing.JRadioButton();
        jrbCorreo = new javax.swing.JRadioButton();
        jrbFijo1 = new javax.swing.JRadioButton();
        jrbCorreo1 = new javax.swing.JRadioButton();
        jbConfirmar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jlErrorEspecialidad = new javax.swing.JLabel();
        jcbEspecialidad = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(671, 580));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jtfNombre.setBorder(null);
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtfNombre);
        jtfNombre.setBounds(51, 119, 250, 24);

        jtfApellido.setBorder(null);
        jtfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfApellido);
        jtfApellido.setBounds(50, 170, 250, 24);

        jtfDni.setBorder(null);
        jtfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDniKeyTyped(evt);
            }
        });
        getContentPane().add(jtfDni);
        jtfDni.setBounds(50, 220, 250, 24);

        jLabelNombre.setText("Nombre *");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(51, 103, 110, 16);

        jLabel2.setText("Apellido *");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 150, 120, 20);

        jLabel3.setText("DNI *");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 203, 100, 20);

        jLabel4.setText("Fecha de Nacimiento *");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 313, 160, 20);

        jLabel5.setText("Celular * (sin 0 ni 15)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 370, 170, 20);

        jLabel7.setText("Sexo *");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 253, 100, 20);

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", "Otro" }));
        jcbSexo.setBorder(null);
        jcbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSexo);
        jcbSexo.setBounds(50, 270, 250, 24);

        jtfCelular.setBorder(null);
        jtfCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCelularKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCelularKeyTyped(evt);
            }
        });
        getContentPane().add(jtfCelular);
        jtfCelular.setBounds(50, 390, 249, 24);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FORMULARIO DE ALTA ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 27);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Complete el siguiente formulario:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(51, 60, 203, 15);

        jLabel13.setText("Tipo de Bombero *");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 153, 130, 20);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voluntario", "Zapador" }));
        jcbTipo.setBorder(null);
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbTipo);
        jcbTipo.setBounds(370, 170, 240, 26);

        jLabel14.setText("Rango *");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 203, 90, 20);

        jcbRango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOMBERO", "CABO", "CABO PRIMERO", "SARGENTO", "SARGENTO 1°", "SUBOFICIAL PRINCIPAL", "SUBOFICIAL MAYOR", "OFICIAL AYUDANTE", "OFICIAL INSPECTOR", "OFICIAL PRINCIPAL", "SUBCOMANDANTE", "COMANDANTE", "COMANDANTE MAYOR", "COMANDANTE GENERAL" }));
        jcbRango.setBorder(null);
        jcbRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRangoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbRango);
        jcbRango.setBounds(370, 220, 240, 25);

        jcbSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jcbSangre.setBorder(null);
        jcbSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSangreActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSangre);
        jcbSangre.setBounds(366, 119, 240, 25);

        jLabel17.setText("Grupo Sanguíneo *");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(366, 105, 150, 12);

        jtfCorreo.setBorder(null);
        jtfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCorreoKeyReleased(evt);
            }
        });
        getContentPane().add(jtfCorreo);
        jtfCorreo.setBounds(450, 450, 160, 24);

        jLabel6.setText("Correo Electrónico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 430, 200, 11);

        jLabel21.setText("Teléfono Fijo (Cód de Área +Nro Telefónico)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(370, 370, 260, 20);

        jtfFijo.setBorder(null);
        jtfFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFijoActionPerformed(evt);
            }
        });
        jtfFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFijoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFijoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfFijo);
        jtfFijo.setBounds(470, 390, 140, 24);
        getContentPane().add(jdcFechaNac);
        jdcFechaNac.setBounds(50, 330, 249, 24);

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcbEstado.setBorder(null);
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbEstado);
        jcbEstado.setBounds(370, 330, 240, 24);

        jLabel22.setText("Estado*");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(370, 318, 90, 10);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("* Campos obligatorios");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(512, 61, 100, 14);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(52, 75, 560, 10);

        jLabel9.setText(" 0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 390, 10, 24);

        jlErrorNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorNombre.setText("!");
        getContentPane().add(jlErrorNombre);
        jlErrorNombre.setBounds(310, 120, 5, 24);

        jlErrorApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorApellido.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorApellido.setText("!");
        getContentPane().add(jlErrorApellido);
        jlErrorApellido.setBounds(310, 170, 5, 17);

        jlErrorDni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorDni.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorDni.setText("!");
        getContentPane().add(jlErrorDni);
        jlErrorDni.setBounds(310, 220, 5, 24);

        jlErrorSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorSexo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorSexo.setText("!");
        getContentPane().add(jlErrorSexo);
        jlErrorSexo.setBounds(310, 270, 5, 24);

        jlErrorFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorFecha.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorFecha.setText("!");
        getContentPane().add(jlErrorFecha);
        jlErrorFecha.setBounds(310, 330, 5, 24);

        jlErrorCelular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorCelular.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorCelular.setText("!");
        getContentPane().add(jlErrorCelular);
        jlErrorCelular.setBounds(310, 390, 5, 24);

        jlErrorFijo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorFijo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorFijo.setText("!");
        getContentPane().add(jlErrorFijo);
        jlErrorFijo.setBounds(620, 390, 5, 24);

        jlErrorCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorCorreo.setText("!");
        getContentPane().add(jlErrorCorreo);
        jlErrorCorreo.setBounds(620, 450, 5, 24);

        jlErrorTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorTipo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorTipo.setText("!");
        getContentPane().add(jlErrorTipo);
        jlErrorTipo.setBounds(620, 170, 5, 24);

        jlErrorSangre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorSangre.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorSangre.setText("!");
        getContentPane().add(jlErrorSangre);
        jlErrorSangre.setBounds(621, 117, 5, 25);

        jlErrorRango.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorRango.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorRango.setText("!");
        getContentPane().add(jlErrorRango);
        jlErrorRango.setBounds(620, 220, 5, 24);

        jlErrorEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorEstado.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorEstado.setText("!");
        getContentPane().add(jlErrorEstado);
        jlErrorEstado.setBounds(620, 330, 5, 24);

        jrbFijo.setText("No");
        jrbFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFijoActionPerformed(evt);
            }
        });
        getContentPane().add(jrbFijo);
        jrbFijo.setBounds(370, 390, 40, 24);

        jrbCorreo.setText("No");
        jrbCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jrbCorreo);
        jrbCorreo.setBounds(370, 450, 47, 24);

        jrbFijo1.setText("Si");
        jrbFijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFijo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbFijo1);
        jrbFijo1.setBounds(410, 390, 40, 24);

        jrbCorreo1.setText("Si");
        jrbCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCorreo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbCorreo1);
        jrbCorreo1.setBounds(410, 450, 39, 24);

        jbConfirmar.setBackground(new java.awt.Color(153, 255, 51));
        jbConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbConfirmar.setText("Confirmar");
        jbConfirmar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbConfirmar.setBorderPainted(false);
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmar);
        jbConfirmar.setBounds(80, 540, 200, 31);

        jbSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbSalir.setBorderPainted(false);
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir);
        jbSalir.setBounds(510, 540, 100, 31);

        jbLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        jbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbLimpiar.setText("Limpiar Campos");
        jbLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbLimpiar.setBorderPainted(false);
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpiar);
        jbLimpiar.setBounds(370, 540, 119, 31);

        jlErrorEspecialidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorEspecialidad.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorEspecialidad.setText("!");
        getContentPane().add(jlErrorEspecialidad);
        jlErrorEspecialidad.setBounds(620, 270, 5, 25);

        jcbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INCENDIO", "RESCATE", "MAT. PELIGROSOS", "INC. FORESTALES", "ACUATICA", "CANINA ", "MONTAÑA", "BUCEO" }));
        jcbEspecialidad.setBorder(null);
        jcbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(jcbEspecialidad);
        jcbEspecialidad.setBounds(370, 270, 240, 25);

        jLabel18.setText("Especialidad *");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 252, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Sólo permite ingreso de letras y hasta 20 caracteres 
    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
   char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != 32)&& (c!='\u00f1')&&(c!='\u00d1')) { 
            evt.consume();
        }

        if (jtfNombre.getText().length() >= 20) { 
            evt.consume();
        }       
    }//GEN-LAST:event_jtfNombreKeyTyped

    // Sólo permite ingreso de números (hasta 10 )
    private void jtfCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCelularKeyTyped
        int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }

    if (jtfCelular.getText().trim().length() == 10) {
        evt.consume();
    }       
    }//GEN-LAST:event_jtfCelularKeyTyped

// Sólo permite ingreso de números (hasta 10 )
    private void jtfFijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFijoKeyTyped
        int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }

    if (jtfFijo.getText().trim().length() == 10) {
        evt.consume();
    }
    }//GEN-LAST:event_jtfFijoKeyTyped

    // Sólo permite ingreso de letras y hasta 19 caracteres 
    private void jtfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != 32)&& (c!='\u00f1')&&(c!='\u00d1')) { 
            evt.consume();
        }

        if (jtfApellido.getText().length() >= 19) { 
            evt.consume();}
    }//GEN-LAST:event_jtfApellidoKeyTyped

    // Sólo permite ingreso de números (hasta 8)
    private void jtfDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyTyped
           int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
         if (!num) {
            evt.consume();}
         if(jtfDni.getText().length() >= 8){
             evt.consume();
        }    
    }//GEN-LAST:event_jtfDniKeyTyped

    private void jtfFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFijoActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jrbFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFijoActionPerformed
        jrbFijo1.setSelected(false);
        jtfFijo.setEnabled(false);
        validacion();
    }//GEN-LAST:event_jrbFijoActionPerformed

    private void jrbFijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFijo1ActionPerformed
        jrbFijo.setSelected(false);
        jtfFijo.setEnabled(true);
        validacion();
        
    }//GEN-LAST:event_jrbFijo1ActionPerformed

    private void jrbCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCorreoActionPerformed
        jrbCorreo1.setSelected(false);
        jtfCorreo.setEnabled(false);
        validacion();
    }//GEN-LAST:event_jrbCorreoActionPerformed

    private void jrbCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCorreo1ActionPerformed
        jrbCorreo.setSelected(false);
        jtfCorreo.setEnabled(true);
        validacion();
    }//GEN-LAST:event_jrbCorreo1ActionPerformed

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        validacion();
    }//GEN-LAST:event_jtfNombreKeyReleased

    private void jtfApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoKeyReleased
        validacion();
    }//GEN-LAST:event_jtfApellidoKeyReleased

    private void jtfDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyReleased
        validacion();
    }//GEN-LAST:event_jtfDniKeyReleased

    private void jtfCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCelularKeyReleased
        validacion();
    }//GEN-LAST:event_jtfCelularKeyReleased

    private void jcbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexoActionPerformed
        validacion();
    }//GEN-LAST:event_jcbSexoActionPerformed

    private void jcbSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSangreActionPerformed
      validacion();
    }//GEN-LAST:event_jcbSangreActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        validacion();
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jcbRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRangoActionPerformed
        validacion();
    }//GEN-LAST:event_jcbRangoActionPerformed

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        validacion();
    }//GEN-LAST:event_jcbEstadoActionPerformed

    private void jtfFijoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFijoKeyReleased
        validacion();
    }//GEN-LAST:event_jtfFijoKeyReleased

    private void jtfCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCorreoKeyReleased
        validacion();
    }//GEN-LAST:event_jtfCorreoKeyReleased

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        BomberoData bdata = new BomberoData();
        Bombero nuevo = new Bombero();
        
        try{
            
            nuevo.setDni(Integer.parseInt(jtfDni.getText()));
            nuevo.setGrupoSanguineo(((String) jcbSangre.getSelectedItem()));
            nuevo.setFechaNacimiento((jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate()));
            nuevo.setCelular((Long.parseLong(jtfCelular.getText())));
            nuevo.setRango((String) jcbRango.getSelectedItem());
            nuevo.setTipo(((String) jcbTipo.getSelectedItem()));
            nuevo.setSexo(((String) jcbSexo.getSelectedItem()));
            nuevo.setEstado((String) jcbEstado.getSelectedItem());
            nuevo.setEspecialidad((String) jcbEspecialidad.getSelectedItem());
           
            
            
            if (jtfNombre.getText().isEmpty()==false && jtfApellido.getText().isEmpty()==false )
            nuevo.setNombreCompleto(jtfNombre.getText() +" " +jtfApellido.getText());
            else 
            nuevo.setNombreCompleto(null);
            
            
            if (jrbFijo1.isSelected())
                nuevo.setFijo(jtfFijo.getText());
            else if (jrbFijo.isSelected())
              nuevo.setFijo(null);
            
            
              if (jrbCorreo1.isSelected())
                nuevo.setCorreo(jtfCorreo.getText());
              else if(jrbCorreo.isSelected())
                nuevo.setCorreo(null); 
            
                
          bdata.altaBombero(nuevo);
           limpiarCampos();
        
        }
        catch(NullPointerException nx){
           JOptionPane.showMessageDialog(this, "Debe completar correctamente todos los campos obligatorios");}
                          
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jcbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecialidadActionPerformed
       validacion();
    }//GEN-LAST:event_jcbEspecialidadActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       validacion();
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaBombero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbEspecialidad;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbRango;
    private javax.swing.JComboBox<String> jcbSangre;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbTipo;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JLabel jlErrorApellido;
    private javax.swing.JLabel jlErrorCelular;
    private javax.swing.JLabel jlErrorCorreo;
    private javax.swing.JLabel jlErrorDni;
    private javax.swing.JLabel jlErrorEspecialidad;
    private javax.swing.JLabel jlErrorEstado;
    private javax.swing.JLabel jlErrorFecha;
    private javax.swing.JLabel jlErrorFijo;
    private javax.swing.JLabel jlErrorNombre;
    private javax.swing.JLabel jlErrorRango;
    private javax.swing.JLabel jlErrorSangre;
    private javax.swing.JLabel jlErrorSexo;
    private javax.swing.JLabel jlErrorTipo;
    private javax.swing.JRadioButton jrbCorreo;
    private javax.swing.JRadioButton jrbCorreo1;
    private javax.swing.JRadioButton jrbFijo;
    private javax.swing.JRadioButton jrbFijo1;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCelular;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfFijo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

public void limpiarCampos(){
        jtfDni.setText(null);
        jtfNombre.setText(null);
        jtfApellido.setText(null);
        jcbSangre.setSelectedItem(null);
        jdcFechaNac.setDate(null);
        jtfCelular.setText(null);
        jtfFijo.setText(null);
        jcbRango.setSelectedItem(null);
        jcbTipo.setSelectedItem(null);
        jcbSexo.setSelectedItem(null);
        jcbEstado.setSelectedItem(null);
        jtfCorreo.setText(null);
        jcbEspecialidad.setSelectedItem(null);
    
        jrbFijo.setSelected(true);
        jrbCorreo.setSelected(true);
        jrbFijo1.setSelected(false);
        jrbCorreo1.setSelected(false);
        jtfFijo.setEnabled(false);
        jtfCorreo.setEnabled(false);
}

    private void validacion(){
        LocalDateTime edadMinima = LocalDateTime.now().minusYears(18);
        
        if (jtfNombre.getText().isEmpty())
            jlErrorNombre.setText("!");
        else 
            jlErrorNombre.setText("");
        
             if (jtfApellido.getText().isEmpty())
            jlErrorApellido.setText("!");
        else 
            jlErrorApellido.setText("");
        
         if (jtfDni.getText().isEmpty())
            jlErrorDni.setText("!");
        else 
            jlErrorDni.setText("");
             
         if (jcbSexo.getSelectedItem()== null)
             jlErrorSexo.setText("!");
           else 
            jlErrorSexo.setText("");
        
         if (jdcFechaNac.getDate()==null)
             jlErrorFecha.setText("!");
          else if (jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime().isAfter(edadMinima))
              jlErrorFecha.setText("!");
           else 
            jlErrorFecha.setText("");
         
          if (jtfCelular.getText().isEmpty())
            jlErrorCelular.setText("!");
        else if (jtfCelular.getText().length()!=10)
             jlErrorCelular.setText("!");
          else
              jlErrorCelular.setText("");
          
           if (jcbSangre.getSelectedItem()== null)
             jlErrorSangre.setText("!");
           else 
            jlErrorSangre.setText("");
           
           if (jcbTipo.getSelectedItem()== null)
             jlErrorTipo.setText("!");
           else 
            jlErrorTipo.setText("");
           
            if (jcbRango.getSelectedItem()== null)
             jlErrorRango.setText("!");
           else 
            jlErrorRango.setText("");
            
             if (jcbEstado.getSelectedItem()== null)
             jlErrorEstado.setText("!");
              else 
            jlErrorEstado.setText("");
             
             if (jcbEspecialidad.getSelectedItem()== null)
             jlErrorEspecialidad.setText("!");
              else 
            jlErrorEspecialidad.setText("");
           
             if(jrbFijo1.isSelected() && (jtfFijo.getText().length() > 9 && jtfFijo.getText().length() < 11))
                 jlErrorFijo.setText("");
             else if (jrbFijo.isSelected())
                 jlErrorFijo.setText("");
             else                 
                 jlErrorFijo.setText("!");
             
              if(jrbCorreo1.isSelected() && jtfCorreo.getText().length() > 6 && jtfCorreo.getText().contains("@") && jtfCorreo.getText().contains("."))
                 jlErrorCorreo.setText("");
              else if (jrbCorreo.isSelected())
                 jlErrorCorreo.setText("");
             else
                 jlErrorCorreo.setText("!");
           
        if (jlErrorNombre.getText().equals("") &&   jlErrorApellido.getText().equals("") &&  jlErrorDni.getText().equals("") && jlErrorSexo.getText().equals("")
                && jlErrorFecha.getText().equals("") && jlErrorCelular.getText().equals("") && jlErrorFijo.getText().equals("") && jlErrorCorreo.getText().equals("")
                && jlErrorSangre.getText().equals("") && jlErrorTipo.getText().equals("") && jlErrorRango.getText().equals("") && jlErrorEstado.getText().equals("") 
                && jlErrorEspecialidad.getText().equals(""))
            
                jbConfirmar.setEnabled(true);
        else 
            jbConfirmar.setEnabled(false);
    }
        
        private void disableCopy(JComponent component) {
        component.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
    }

    private void disablePaste(JComponent component) {
        component.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");
    }

    private void disableCopyPaste(JComponent component) {
        disableCopy(component);
        disablePaste(component);

    }

}


