/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ignis66.vistas;

import Ignis66.acessoADatos.BomberoData;
import Ignis66.acessoADatos.Conexion;
import Ignis66.entidades.Bombero;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fdicocco
 */
public class ModificarBombero extends javax.swing.JFrame {
      private DefaultTableModel modelo = new DefaultTableModel(){
                @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        };
};
    /**
     * Creates new form PruebaModificarBombero
     */
    public ModificarBombero() {
        initComponents();
        modelarTabla();
        cargarTabla();
        validacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfBuscarNombre = new javax.swing.JTextField();
        jtfCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jtfIdBombero = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jcbSexo = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JComboBox<>();
        jcbSangre = new javax.swing.JComboBox<>();
        jcbTipo = new javax.swing.JComboBox<>();
        jtfFijo2 = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jcbRango = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlErrorNombre = new javax.swing.JLabel();
        jlErrorDni = new javax.swing.JLabel();
        jlErrorSexo = new javax.swing.JLabel();
        jlErrorFecha = new javax.swing.JLabel();
        jlErrorSangre = new javax.swing.JLabel();
        jlErrorCelular = new javax.swing.JLabel();
        jlErrorTipo = new javax.swing.JLabel();
        jlErrorRango = new javax.swing.JLabel();
        jlErrorEstado = new javax.swing.JLabel();
        jlErrorCorreo = new javax.swing.JLabel();
        jlErrorFijo = new javax.swing.JLabel();
        jrbCorreo = new javax.swing.JRadioButton();
        jrbCorreo1 = new javax.swing.JRadioButton();
        jrbFijo = new javax.swing.JRadioButton();
        jrbFijo1 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jtfCorreo2 = new javax.swing.JTextField();
        jcbEspecialidad = new javax.swing.JComboBox<>();
        jlErrorEspecialidad = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        jLabel27.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel27.setText("(*) Campos obligatorios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ACTUALIZACION DE DATOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("Introduza el nombre y/o apellido:");

        jtfBuscarNombre.setBorder(null);
        jtfBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarNombreKeyTyped(evt);
            }
        });

        jtfCelular.setBorder(null);
        jtfCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCelularKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCelularKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Sexo *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Correo Electrónico");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("Teléfono Fijo (Cód. de Área + Nro Tel)");

        jtfNombre.setBorder(null);
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Nombre Completo *");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("Grupo Sanguíneo *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("DNI *");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento *");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Celular (sin 0 ni 15) *");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("Tipo de Bombero *");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setText("Rango *");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("Estado *");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE Y APELLIDO", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setText("ID del Bombero");

        jtfIdBombero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfIdBombero.setText("-");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("* Campos obligatorios");

        jtfDni.setBorder(null);
        jtfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDniKeyTyped(evt);
            }
        });

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", "Otro" }));
        jcbSexo.setBorder(null);
        jcbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexoActionPerformed(evt);
            }
        });

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcbEstado.setBorder(null);
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });

        jcbSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jcbSangre.setBorder(null);
        jcbSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSangreActionPerformed(evt);
            }
        });

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voluntario", "Zapador" }));
        jcbTipo.setBorder(null);
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });

        jtfFijo2.setBorder(null);
        jtfFijo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFijo2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFijo2KeyTyped(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbSalir.setBorderPainted(false);
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        jbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbLimpiar.setText("Limpiar Campos");
        jbLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbLimpiar.setBorderPainted(false);
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(153, 255, 51));
        jbActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white));
        jbActualizar.setBorderPainted(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jcbRango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOMBERO", "CABO", "CABO PRIMERO", "SARGENTO", "SARGENTO 1°", "SUBOFICIAL PRINCIPAL", "SUBOFICIAL MAYOR", "OFICIAL AYUDANTE", "OFICIAL INSPECTOR", "OFICIAL PRINCIPAL", "SUBCOMANDANTE", "COMANDANTE", "COMANDANTE MAYOR", "COMANDANTE GENERAL" }));
        jcbRango.setBorder(null);
        jcbRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRangoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Seleccione de la tabla el bombero cuyos datos desea actualizar:");

        jlErrorNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorNombre.setText("!");

        jlErrorDni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorDni.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorDni.setText("!");

        jlErrorSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorSexo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorSexo.setText("!");

        jlErrorFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorFecha.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorFecha.setText("!");

        jlErrorSangre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorSangre.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorSangre.setText("!");

        jlErrorCelular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorCelular.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorCelular.setText("!");

        jlErrorTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorTipo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorTipo.setText("!");

        jlErrorRango.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorRango.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorRango.setText("!");

        jlErrorEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorEstado.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorEstado.setText("!");

        jlErrorCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorCorreo.setText("!");

        jlErrorFijo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorFijo.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorFijo.setText("!");

        jrbCorreo.setText("No");
        jrbCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCorreoActionPerformed(evt);
            }
        });

        jrbCorreo1.setText("Si");
        jrbCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCorreo1ActionPerformed(evt);
            }
        });

        jrbFijo.setText("No");
        jrbFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFijoActionPerformed(evt);
            }
        });

        jrbFijo1.setText("Si");
        jrbFijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFijo1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setText("0");

        jtfCorreo2.setBorder(null);
        jtfCorreo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCorreo2KeyReleased(evt);
            }
        });

        jcbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INCENDIO", "RESCATE", "MAT. PELIGROSOS", "INC. FORESTALES", "ACUATICA", "CANINA ", "MONTAÑA", "BUCEO" }));
        jcbEspecialidad.setBorder(null);
        jcbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecialidadActionPerformed(evt);
            }
        });

        jlErrorEspecialidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorEspecialidad.setForeground(new java.awt.Color(255, 0, 0));
        jlErrorEspecialidad.setText("!");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("Especialidad *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(jlErrorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfDni, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbRango, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(4, 4, 4)
                                                .addComponent(jlErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlErrorSexo)
                                                    .addComponent(jlErrorDni)
                                                    .addComponent(jlErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlErrorRango, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(98, 98, 98))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtfCelular, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jcbSangre, 0, 210, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlErrorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlErrorSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jtfBuscarNombre)
                                    .addComponent(jLabel13)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel6))
                                                .addGap(61, 61, 61))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jrbCorreo)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jrbCorreo1)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jtfCorreo2))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jrbFijo)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jrbFijo1)
                                                            .addGap(8, 8, 8)
                                                            .addComponent(jLabel29)
                                                            .addGap(5, 5, 5)
                                                            .addComponent(jtfFijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(jLabel25)
                                                                .addGap(198, 198, 198))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                        .addComponent(jlErrorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlErrorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlErrorFijo))
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlErrorEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jtfIdBombero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel26)
                                .addGap(0, 0, 0)
                                .addComponent(jtfIdBombero, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlErrorDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlErrorSexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel24)))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlErrorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jtfBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlErrorSangre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlErrorCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlErrorTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbRango, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlErrorRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlErrorEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlErrorEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlErrorCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbCorreo)
                            .addComponent(jrbCorreo1)
                            .addComponent(jtfCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlErrorFijo)
                            .addComponent(jrbFijo)
                            .addComponent(jrbFijo1)
                            .addComponent(jLabel29))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jtfBuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarNombreKeyReleased
 buscarNombre(jtfBuscarNombre.getText());
        
    }//GEN-LAST:event_jtfBuscarNombreKeyReleased

    private void jtfCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCelularKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (jtfCelular.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCelularKeyTyped

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != 32)&& (c!='\u00f1')&&(c!='\u00d1')) {
            evt.consume();
        }

        if (jtfNombre.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int seleccion = jTable1.getSelectedRow();
         
         BomberoData bdata = new BomberoData();
         String idBomb = jTable1.getValueAt(seleccion, 0).toString();
         int idB = Integer.parseInt(idBomb);
         Bombero b = bdata.traerDatos(idB);
         jtfIdBombero.setText(idB+"");
         jtfNombre.setText(b.getNombreCompleto());
         jtfDni.setText(String.valueOf(b.getDni()));
         jtfCelular.setText(Long.toString(b.getCelular())); 
         jtfFijo2.setText(b.getFijo());
         jtfCorreo2.setText(b.getCorreo());
         jcbEstado.setSelectedItem(b.getEstado());
         jcbEspecialidad.setSelectedItem(b.getEspecialidad());
         jcbSexo.setSelectedItem(b.getSexo());
         jdcFechaNac.setDate(Date.from(b.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant()));
         jcbSangre.setSelectedItem(b.getGrupoSanguineo());
         jcbTipo.setSelectedItem(b.getTipo());
         jcbRango.setSelectedItem(b.getRango());
         
         if(b.getCorreo()==null){
             jrbCorreo.setSelected(true);
             jrbCorreo1.setSelected(false);
             jtfCorreo2.setEnabled(false);
          } else{
             jrbCorreo.setSelected(false);  
             jrbCorreo1.setSelected(true);
              jtfCorreo2.setEnabled(true);
         }
         
         if(b.getFijo()==null){
             jrbFijo.setSelected(true);
             jrbFijo1.setSelected(false);
              jtfFijo2.setEnabled(false);
          } else{
             jrbFijo.setSelected(false);  
             jrbFijo1.setSelected(true);
             jtfFijo2.setEnabled(true);
         }
         
         validacion();

    }//GEN-LAST:event_jTable1MouseClicked

    private void jtfDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyTyped
           int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
         if (!num) {
            evt.consume();}
         if(jtfDni.getText().length() >= 8){
             evt.consume();
        }    
    }//GEN-LAST:event_jtfDniKeyTyped

    private void jtfBuscarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != 32)&& (c!='\u00f1')&&(c!='\u00d1')) {
            evt.consume();
        }

        if (jtfBuscarNombre.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfBuscarNombreKeyTyped

    private void jtfFijo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFijo2KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (jtfFijo2.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfFijo2KeyTyped

    private void jcbSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSangreActionPerformed
        validacion();
    }//GEN-LAST:event_jcbSangreActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        validacion();
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        
         BomberoData bdata = new BomberoData();    
         Bombero bm = new Bombero(); 
        
         try{
         bm.setEstado((String)jcbEstado.getSelectedItem());
         bm.setNombreCompleto(jtfNombre.getText());
         bm.setDni(Integer.parseInt(jtfDni.getText()));
         bm.setCelular(Long.parseLong(jtfCelular.getText())); 
         
         if (jrbFijo1.isSelected())
             bm.setFijo(jtfFijo2.getText());
         else
             bm.setFijo(null);
         
         if (jrbCorreo1.isSelected())
             bm.setCorreo(jtfCorreo2.getText());
         else
             bm.setCorreo(null);
         
         bm.setSexo((String) jcbSexo.getSelectedItem());
         bm.setFechaNacimiento(jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
         bm.setGrupoSanguineo((String) jcbSangre.getSelectedItem());
         bm.setTipo((String) jcbTipo.getSelectedItem());
         bm.setEspecialidad((String) jcbEspecialidad.getSelectedItem());
         bm.setRango((String) jcbRango.getSelectedItem());
         
         bdata.modificarDatosBombero(bm, Integer.parseInt(jtfIdBombero.getText()));
     
         limpiarCampos();
         limpiarTabla();
         cargarTabla();
         }
        catch(NumberFormatException nx){
           JOptionPane.showMessageDialog(this, "Error al intentar carga el número de celular. Intente nuevamente.");}
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jrbCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCorreoActionPerformed
         jrbCorreo1.setSelected(false);
         jtfCorreo2.setEnabled(false);
        validacion();
        
    }//GEN-LAST:event_jrbCorreoActionPerformed

    private void jrbCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCorreo1ActionPerformed
         jrbCorreo.setSelected(false);
         jtfCorreo2.setEnabled(true);
        validacion();
    }//GEN-LAST:event_jrbCorreo1ActionPerformed

    private void jrbFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFijoActionPerformed
        jrbFijo1.setSelected(false);
         jtfFijo2.setEnabled(false);
        validacion();    }//GEN-LAST:event_jrbFijoActionPerformed

    private void jrbFijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFijo1ActionPerformed
        jrbFijo.setSelected(false);
        jtfFijo2.setEnabled(true);
        validacion();  
    }//GEN-LAST:event_jrbFijo1ActionPerformed

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        validacion();
    }//GEN-LAST:event_jtfNombreKeyReleased

    private void jtfDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyReleased
         validacion();
    }//GEN-LAST:event_jtfDniKeyReleased

    private void jcbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexoActionPerformed
         validacion();
    }//GEN-LAST:event_jcbSexoActionPerformed

    private void jtfCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCelularKeyReleased
         validacion();
    }//GEN-LAST:event_jtfCelularKeyReleased

    private void jcbRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRangoActionPerformed
         validacion();
    }//GEN-LAST:event_jcbRangoActionPerformed

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
         validacion();
    }//GEN-LAST:event_jcbEstadoActionPerformed

    private void jtfFijo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFijo2KeyReleased
         validacion();
    }//GEN-LAST:event_jtfFijo2KeyReleased

    private void jtfCorreo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCorreo2KeyReleased
        validacion();
    }//GEN-LAST:event_jtfCorreo2KeyReleased

    private void jcbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecialidadActionPerformed
        validacion();
    }//GEN-LAST:event_jcbEspecialidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarBombero().setVisible(true);
            }
        });
    
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarBombero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbEspecialidad;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbRango;
    private javax.swing.JComboBox<String> jcbSangre;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbTipo;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JLabel jlErrorCelular;
    private javax.swing.JLabel jlErrorCorreo;
    private javax.swing.JLabel jlErrorDni;
    private javax.swing.JLabel jlErrorEspecialidad;
    private javax.swing.JLabel jlErrorEstado;
    private javax.swing.JLabel jlErrorFecha;
    private javax.swing.JLabel jlErrorFijo;
    private javax.swing.JLabel jlErrorNombre;
    private javax.swing.JLabel jlErrorRango;
    private javax.swing.JLabel jlErrorSangre;
    private javax.swing.JLabel jlErrorSexo;
    private javax.swing.JLabel jlErrorTipo;
    private javax.swing.JRadioButton jrbCorreo;
    private javax.swing.JRadioButton jrbCorreo1;
    private javax.swing.JRadioButton jrbFijo;
    private javax.swing.JRadioButton jrbFijo1;
    private javax.swing.JTextField jtfBuscarNombre;
    private javax.swing.JTextField jtfCelular;
    private javax.swing.JTextField jtfCorreo2;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfFijo2;
    private javax.swing.JLabel jtfIdBombero;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

public void buscarNombre(String nombreBuscado){
    String sql = "SELECT idBombero, nombreCompleto, dni FROM bomberos WHERE nombreCompleto LIKE '%" + nombreBuscado + "%'";
    limpiarTabla();
    try{
        PreparedStatement ps = Conexion.getConexion().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            modelo.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
            rs.close();
            ps.close();
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(null, "Error en la carga de datos " + sqle.getMessage());
        }
}    
        
public void cargarTabla(){
    limpiarCampos();
     BomberoData bdata = new BomberoData();    
    for ( Bombero bomb : bdata.listarBomberos())
          modelo.addRow(new Object[]{bomb.getIdBombero(),bomb.getNombreCompleto(),bomb.getDni()});
    }

 private void modelarTabla(){
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE Y APELLIDO");
        modelo.addColumn("DNI");
        
        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(38);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(155);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
    }

 private void limpiarTabla(){
             int i = 0; 
        while (modelo.getRowCount() !=0)
        modelo.removeRow(i);
 }
 
 private void limpiarCampos(){
         jtfIdBombero.setText(null);
         jtfNombre.setText(null);
         jtfDni.setText(null);
         jtfCelular.setText(null); 
         jtfFijo2.setText(null);
         jtfCorreo2.setText(null);
         jcbEstado.setSelectedItem(null);
         jcbEspecialidad.setSelectedItem(null);
         jcbSexo.setSelectedItem(null);
         jdcFechaNac.setDate(null);
         jcbSangre.setSelectedItem(null);
         jcbTipo.setSelectedItem(null);
         jcbRango.setSelectedItem(null);
         jtfBuscarNombre.setText(null);
         jrbFijo.setSelected(true);
         jrbCorreo.setSelected(true);
         jrbFijo1.setSelected(false);
         jrbCorreo1.setSelected(false);
         jtfFijo2.setEnabled(false);
         jtfCorreo2.setEnabled(false);

       
 }
 
 private void validacion(){
        if (jtfNombre.getText().isEmpty())
            jlErrorNombre.setText("!");
        else 
            jlErrorNombre.setText("");
        
         if (jtfDni.getText().isEmpty())
            jlErrorDni.setText("!");
        else 
            jlErrorDni.setText("");
             
         if (jcbSexo.getSelectedItem()== null)
             jlErrorSexo.setText("!");
           else 
            jlErrorSexo.setText("");
        
         if (jdcFechaNac.getDate()==null)
             jlErrorFecha.setText("!");
           else 
            jlErrorFecha.setText("");
         
          if (jtfCelular.getText().isEmpty())
            jlErrorCelular.setText("!");
        else if (jtfCelular.getText().length()!=10)
             jlErrorCelular.setText("!");
          else
              jlErrorCelular.setText("");
          
           if (jcbSangre.getSelectedItem()== null)
             jlErrorSangre.setText("!");
           else 
            jlErrorSangre.setText("");
           
           if (jcbTipo.getSelectedItem()== null)
             jlErrorTipo.setText("!");
           else 
            jlErrorTipo.setText("");
           
            if (jcbRango.getSelectedItem()== null)
             jlErrorRango.setText("!");
           else 
            jlErrorRango.setText("");
            
             if (jcbEstado.getSelectedItem()== null)
             jlErrorEstado.setText("!");
              else 
            jlErrorEstado.setText("");
             
             if (jcbEspecialidad.getSelectedItem()== null)
             jlErrorEspecialidad.setText("!");
              else 
            jlErrorEspecialidad.setText("");
           
             if(jrbFijo1.isSelected() && (jtfFijo2.getText().length() > 9 && jtfFijo2.getText().length() < 11))
                 jlErrorFijo.setText("");
             else if (jrbFijo.isSelected())
                 jlErrorFijo.setText("");
             else                 
                 jlErrorFijo.setText("!");
             
              if(jrbCorreo1.isSelected() && jtfCorreo2.getText().length() > 6 && jtfCorreo2.getText().contains("@") && jtfCorreo2.getText().contains("."))
                 jlErrorCorreo.setText("");
              else if (jrbCorreo.isSelected())
                 jlErrorCorreo.setText("");
             else
                 jlErrorCorreo.setText("!");
           
        if (jlErrorNombre.getText().equals("") &&   jlErrorDni.getText().equals("") &&  jlErrorDni.getText().equals("") && jlErrorSexo.getText().equals("")
                && jlErrorFecha.getText().equals("") && jlErrorCelular.getText().equals("") && jlErrorFijo.getText().equals("") && jlErrorCorreo.getText().equals("")
                && jlErrorSangre.getText().equals("") && jlErrorTipo.getText().equals("") && jlErrorRango.getText().equals("") && jlErrorEstado.getText().equals("")
                &&  jlErrorEspecialidad.getText().equals(""))
            
                jbActualizar.setEnabled(true);
        else 
            jbActualizar.setEnabled(false);
    }
        
 
}
